In [194]:
import pandas as pd
import numpy as np
import torch

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
!pip install sklearn.preprocessing

Requirement already satisfied: sklearn.preprocessing in /usr/local/lib/python3.13/dist-packages (0.1.0)

In [197]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [198]:
import kagglehub

path = kagglehub.dataset_download("yasserh/breast-cancer-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/yasserh/breast-cancer-dataset/1.archive...

100%|██████████| 48.6k/48.6k [00:00<00:00, 41.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/yasserh/breast-cancer-dataset/versions/1

In [199]:
import os

files = [f for f in os.listdir(path) if f.endswith('.csv')]
if files:
    csv_path = os.path.join(path, files[0])
    df = pd.read_csv(csv_path)
    print("Successfully loaded dataset from:", csv_path)
else:
    print("No CSV files found in directory:", path)

Successfully loaded dataset from: /root/.cache/kagglehub/datasets/yasserh/breast-cancer-dataset/versions/1/breast-cancer.csv

In [200]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [201]:
df.shape

(569, 32)

In [202]:
df.drop(columns=['id'],inplace=True)

In [203]:
df.shape

(569, 31)

train test split

In [204]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [205]:
scaler=StandardScaler()

In [206]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [207]:
X_train #x is converted into 1d

array([[-0.2321161 , -0.6655394 , -0.25947162, ..., -0.40256151,
        -1.371751  , -0.45075242],
       [ 1.79965197,  0.48758671,  1.84906304, ...,  1.44863637,
        -0.67253758,  0.33412518],
       [-0.93845098,  0.54464862, -0.97686281, ..., -1.7702421 ,
        -0.70814567, -1.04384739],
       ...,
       [ 0.02677956, -0.56330348, -0.08817867, ..., -1.26250325,
        -0.70814567, -1.31406053],
       [-0.40096109,  0.52800557, -0.42587049, ..., -1.04313813,
        -1.159721  , -0.88412394],
       [ 0.92165802,  1.3054741 ,  0.96404946, ...,  0.85147576,
        -1.19047345,  0.50644331]])

In [208]:
y_train

124    B
499    M
550    B
33     M
487    M
      ..
473    B
523    B
270    B
191    B
168    M
Name: diagnosis, Length: 455, dtype: object

In [209]:
y_test

466    B
231    B
152    B
70     M
457    B
      ..
139    B
545    B
565    M
548    B
66     B
Name: diagnosis, Length: 114, dtype: object

y is not lable encoded So,LableEncode the y

In [210]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [211]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

numpy array to pytorch tensors

In [212]:
x_train_tensor=torch.from_numpy(X_train)
x_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [213]:
x_train_tensor.shape #it has 30 features hence it would have 30 bias

torch.Size([455, 30])

Defining the model

defining parameters

In [214]:
learning_rate=1e-3
epochs=25

Training Pipeline

In [215]:
# Redefine class with correct spelling to fix the initialization error
class MyNN():
        def __init__(self, x):
                self.weights = torch.rand(x.shape[1], dtype=torch.double, requires_grad=True)
                self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        def forward(self,x):
                z=torch.matmul(x,self.weights)+self.bias
                y_pred=torch.sigmoid(z)
                return y_pred
        def loss_function(self,y_pred,y):
                #clamp prediction to avoid log(0)
                epsilon=1e-7
                y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
                #calculate loss
                loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()


                return loss

# create model
model = MyNN(x_train_tensor)

#define loop
for epoch in range(epochs):
      #forward pass
        y_pred=model.forward(x_train_tensor)
      #loss function
        loss=model.loss_function(y_pred,y_train_tensor)

      #backward pass
        loss.backward()
      # parameter updation
        with torch.no_grad():
                 model.weights-=learning_rate*model.weights.grad
                 model.bias-=learning_rate*model.bias.grad

        #zero gradients
        model.weights.grad.zero_()

        model.bias.grad.zero_()
        #print loss in each epoch
        print(f"Epoch : {epoch+1} , Loss: {loss.item()}")

Epoch : 1 , Loss: 0.4915757898807449
Epoch : 2 , Loss: 0.49145238830695764
Epoch : 3 , Loss: 0.4913290123338736
Epoch : 4 , Loss: 0.49120566195626664
Epoch : 5 , Loss: 0.4910823371725045
Epoch : 6 , Loss: 0.4909590379779767
Epoch : 7 , Loss: 0.49083576437195275
Epoch : 8 , Loss: 0.4907125163503793
Epoch : 9 , Loss: 0.49058929391125616
Epoch : 10 , Loss: 0.4904660970477607
Epoch : 11 , Loss: 0.49034292575474464
Epoch : 12 , Loss: 0.4902197800333643
Epoch : 13 , Loss: 0.4900966598778336
Epoch : 14 , Loss: 0.4899735652860999
Epoch : 15 , Loss: 0.4898504962566278
Epoch : 16 , Loss: 0.489727452780906
Epoch : 17 , Loss: 0.4896044348599131
Epoch : 18 , Loss: 0.48948144248961
Epoch : 19 , Loss: 0.4893584756642887
Epoch : 20 , Loss: 0.48923553438045847
Epoch : 21 , Loss: 0.4891126186390982
Epoch : 22 , Loss: 0.4889897284337174
Epoch : 23 , Loss: 0.48886686376375854
Epoch : 24 , Loss: 0.48874402462007077
Epoch : 25 , Loss: 0.48862121100288686

In [216]:
print(model.weights) #better weights and bias than random given weights and bias
print(model.bias)

tensor([0.7451, 0.2331, 0.7189, 0.6676, 0.3736, 0.8527, 0.4859, 0.2481, 0.4335,
        0.8157, 0.9455, 0.1591, 0.7896, 0.7767, 0.4914, 0.6320, 0.0872, 0.9850,
        0.5144, 0.4275, 0.9613, 0.9631, 0.6877, 0.5998, 0.5825, 0.6897, 0.9576,
        0.0280, 0.9046, 0.7597], dtype=torch.float64, requires_grad=True)
tensor([-0.0003], dtype=torch.float64, requires_grad=True)

## Evaluation

In [219]:
with torch.no_grad():
     y_pred=model.forward(x_test_tensor)
     y_pred=(y_pred > 0.5).float()
     accuracy=(y_pred==y_test_tensor).float().mean()
print(f"Accuracy : {accuracy}")
print(((y_pred)==1).sum().item()) #total 46 >
print(y_pred.shape)

Accuracy : 0.9298245906829834
36
torch.Size([114])