In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
import kagglehub

path = kagglehub.dataset_download("yasserh/breast-cancer-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'breast-cancer-dataset' dataset.
Path to dataset files: /kaggle/input/breast-cancer-dataset

In [5]:
import os

files = [f for f in os.listdir(path) if f.endswith('.csv')]
if files:
    csv_path = os.path.join(path, files[0])
    df = pd.read_csv(csv_path)
    print("Successfully loaded dataset from:", csv_path)
else:
    print("No CSV files found in directory:", path)

Successfully loaded dataset from: /kaggle/input/breast-cancer-dataset/breast-cancer.csv

In [6]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
df.shape

(569, 32)

In [8]:
df.drop(columns=['id'],inplace=True)

In [9]:
df.shape

(569, 31)

train test split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [11]:
scaler=StandardScaler()

In [12]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
X_train #x is converted into 1d

array([[-0.20407187, -0.27349972, -0.23302163, ..., -0.552856  ,
        -0.33010735, -0.96238156],
       [ 1.2794028 , -0.55140956,  1.20970192, ...,  0.79291518,
         0.02189064,  0.0260004 ],
       [-0.31796628, -1.3239047 , -0.39429159, ..., -1.22033045,
        -1.26062056, -0.97464966],
       ...,
       [ 0.09490095, -2.0186793 ,  0.08537253, ...,  0.10242436,
         0.01374253, -0.2140276 ],
       [-1.39483792, -1.55235601, -1.2740213 , ..., -0.19633105,
         0.25655596,  2.19371991],
       [ 1.02029302,  2.01807886,  1.03972587, ...,  1.24409682,
         0.14900102,  0.35617224]])

In [14]:
y_train

93     B
121    M
309    B
262    M
260    M
      ..
226    B
235    B
123    B
504    B
446    M
Name: diagnosis, Length: 455, dtype: object

In [15]:
y_test

454    B
263    M
108    M
529    B
457    B
      ..
418    B
243    B
355    B
0      M
12     M
Name: diagnosis, Length: 114, dtype: object

y is not lable encoded So,LableEncode the y

In [16]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [17]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

numpy array to pytorch tensors

In [18]:
x_train_tensor=torch.from_numpy(X_train)
x_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [19]:
x_train_tensor.shape #it has 30 features hence it would have 30 bias

torch.Size([455, 30])

Defining the model

defining parameters

In [20]:
learning_rate=1e-3
epochs=25

In [27]:
from torch.utils.data import Dataset,DataLoader

class MyData(Dataset):
  def __init__(self,features,lables):
    self.features=features
    self.labels=lables
  def __len__(self):
    return self.labels.shape[0]
  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [29]:
train_dataset=MyData(x_train_tensor,y_train_tensor)
test_dataset=MyData(x_test_tensor,y_test_tensor)

In [30]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

Training Pipeline

In [31]:
class MyNN(torch.nn.Module):
        def __init__(self, x):
                super().__init__()
                self.weights = torch.nn.Parameter(torch.rand(x.shape[1], dtype=torch.double, requires_grad=True))
                self.bias = torch.nn.Parameter(torch.zeros(1, dtype=torch.float64, requires_grad=True))
        def forward(self,x):
                z=torch.matmul(x,self.weights)+self.bias
                y_pred=torch.sigmoid(z)
                return y_pred
        def loss_function(self,y_pred,y):
                #clamp prediction to avoid log(0)
                epsilon=1e-7
                y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
                #calculate loss
                loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
                return loss

# create model
model = MyNN(x_train_tensor)

# Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

'''#define loop
for epoch in range(epochs):
      #forward pass
        y_pred=model.forward(x_train_tensor)
      #loss function
        loss=model.loss_function(y_pred,y_train_tensor)

      #backward pass
        loss.backward()
      # parameter updation
        with torch.no_grad():
                 model.weights-=learning_rate*model.weights.grad
                 model.bias-=learning_rate*model.bias.grad

        #zero gradients
        model.weights.grad.zero_()

        model.bias.grad.zero_()
        #print loss in each epoch
        print(f"Epoch : {epoch+1} , Loss: {loss.item()}")'''


for epoch in range(epochs):
  for batch_feature,batch_label in train_loader:

      # forward pass
      y_pred=model(batch_feature)

      #loss calculation (calling the method on our model instance)
      loss=model.loss_function(y_pred,batch_label.view(-1,1))

      #clear_grad
      optimizer.zero_grad()

      #backward pass
      loss.backward()

      #parameter_updation
      optimizer.step()

      print(f"Epoch: {epoch+1},Loss : {loss.item()}")

Epoch: 1,Loss : 3.1216481692297124
Epoch: 1,Loss : 4.417315879167448
Epoch: 1,Loss : 4.18927946106526
Epoch: 1,Loss : 3.2244676220426527
Epoch: 1,Loss : 3.7130665212451195
Epoch: 1,Loss : 3.433711298038107
Epoch: 1,Loss : 4.338448216156495
Epoch: 1,Loss : 3.9357143498764398
Epoch: 1,Loss : 3.7998871872060134
Epoch: 1,Loss : 3.1169117028326205
Epoch: 1,Loss : 3.4386714490837513
Epoch: 1,Loss : 3.375344307610007
Epoch: 1,Loss : 4.360120435211676
Epoch: 1,Loss : 3.616086907134495
Epoch: 1,Loss : 2.6957922909718244
Epoch: 2,Loss : 3.5359717850684946
Epoch: 2,Loss : 4.328407847024778
Epoch: 2,Loss : 3.761053027670436
Epoch: 2,Loss : 4.105149534091769
Epoch: 2,Loss : 4.019477194098594
Epoch: 2,Loss : 3.2195338651347067
Epoch: 2,Loss : 3.0214441280759323
Epoch: 2,Loss : 4.440929351948057
Epoch: 2,Loss : 3.5588058326394068
Epoch: 2,Loss : 3.785353670163083
Epoch: 2,Loss : 3.748695321109411
Epoch: 2,Loss : 3.8776804074343394
Epoch: 2,Loss : 3.350846139223948
Epoch: 2,Loss : 3.807059797889319
Epoch: 2,Loss : 2.876421450507511
Epoch: 3,Loss : 3.788610700137379
Epoch: 3,Loss : 4.3139097602383885
Epoch: 3,Loss : 3.4396663818763082
Epoch: 3,Loss : 4.129853354035971
Epoch: 3,Loss : 3.1135434401445323
Epoch: 3,Loss : 3.6931476769533447
Epoch: 3,Loss : 3.292788185152063
Epoch: 3,Loss : 3.6152937004140795
Epoch: 3,Loss : 3.1585169987857276
Epoch: 3,Loss : 3.9623422157653736
Epoch: 3,Loss : 4.630181729172286
Epoch: 3,Loss : 3.9692611600686796
Epoch: 3,Loss : 3.5337647555502745
Epoch: 3,Loss : 3.3214039454998097
Epoch: 3,Loss : 3.4010298592927204
Epoch: 4,Loss : 3.2985579652098576
Epoch: 4,Loss : 3.1698413664981517
Epoch: 4,Loss : 4.06717932319413
Epoch: 4,Loss : 3.4592607983061288
Epoch: 4,Loss : 3.340286907109631
Epoch: 4,Loss : 4.196234713724167
Epoch: 4,Loss : 4.188298335375994
Epoch: 4,Loss : 3.0697912261243143
Epoch: 4,Loss : 4.131842145590301
Epoch: 4,Loss : 3.4890455016933144
Epoch: 4,Loss : 3.640759023901605
Epoch: 4,Loss : 3.9193483375426763
Epoch: 4,Loss : 3.613089795311617
Epoch: 4,Loss : 3.861900008647711
Epoch: 4,Loss : 4.273208115837424
Epoch: 5,Loss : 3.4074954493125484
Epoch: 5,Loss : 3.9729693709314056
Epoch: 5,Loss : 3.7345466307729898
Epoch: 5,Loss : 4.134439056527704
Epoch: 5,Loss : 3.9143247880022645
Epoch: 5,Loss : 3.455248926304895
Epoch: 5,Loss : 4.02076999179434
Epoch: 5,Loss : 4.308717237546404
Epoch: 5,Loss : 3.8335733268208303
Epoch: 5,Loss : 3.1406451852905284
Epoch: 5,Loss : 3.309801307342741
Epoch: 5,Loss : 3.964295649039368
Epoch: 5,Loss : 2.9078742255903265
Epoch: 5,Loss : 3.265409016294858
Epoch: 5,Loss : 1.8750776719912121
Epoch: 6,Loss : 3.9612450458055974
Epoch: 6,Loss : 3.5461477011242124
Epoch: 6,Loss : 2.806240656977881
Epoch: 6,Loss : 3.5179181930263983
Epoch: 6,Loss : 4.411065099483549
Epoch: 6,Loss : 4.109048577631449
Epoch: 6,Loss : 3.598107855400672
Epoch: 6,Loss : 3.7076354697120233
Epoch: 6,Loss : 4.205813499242668
Epoch: 6,Loss : 3.316184482092216
Epoch: 6,Loss : 3.2315611610803305
Epoch: 6,Loss : 3.7628139868982715
Epoch: 6,Loss : 3.7424396398017095
Epoch: 6,Loss : 3.4918892685425766
Epoch: 6,Loss : 2.941690963008841
Epoch: 7,Loss : 3.8560391105982075
Epoch: 7,Loss : 4.346559130464647
Epoch: 7,Loss : 3.2670606272797333
Epoch: 7,Loss : 3.8606988763671835
Epoch: 7,Loss : 4.124174696736384
Epoch: 7,Loss : 3.560050874199389
Epoch: 7,Loss : 3.916471348286657
Epoch: 7,Loss : 2.818107699288522
Epoch: 7,Loss : 3.968433008184194
Epoch: 7,Loss : 4.234756002693351
Epoch: 7,Loss : 3.3140932083944024
Epoch: 7,Loss : 3.0305915210127568
Epoch: 7,Loss : 3.390482107146726
Epoch: 7,Loss : 3.1400468510698447
Epoch: 7,Loss : 4.201202921408269
Epoch: 8,Loss : 3.1319036125913606
Epoch: 8,Loss : 3.775721875421926
Epoch: 8,Loss : 3.9956448260560427
Epoch: 8,Loss : 3.2165983645412157
Epoch: 8,Loss : 3.283498390486744
Epoch: 8,Loss : 1.6290982597785306
Epoch: 8,Loss : 3.552459245639947
Epoch: 8,Loss : 3.7287562975460764
Epoch: 8,Loss : 3.53586231953712
Epoch: 8,Loss : 4.400624781003097
Epoch: 8,Loss : 3.839630630431828
Epoch: 8,Loss : 3.8243245420669836
Epoch: 8,Loss : 3.631149619268915
Epoch: 8,Loss : 4.116804642350643
Epoch: 8,Loss : 3.8889443530832453
Epoch: 9,Loss : 3.2287193495774726
Epoch: 9,Loss : 3.775348764797792
Epoch: 9,Loss : 3.6955705839042388
Epoch: 9,Loss : 2.975913050600939
Epoch: 9,Loss : 3.501341434535297
Epoch: 9,Loss : 4.094866738339942
Epoch: 9,Loss : 4.079671029574306
Epoch: 9,Loss : 3.4820163658078185
Epoch: 9,Loss : 3.2520098582252874
Epoch: 9,Loss : 3.7006001995937092
Epoch: 9,Loss : 3.9325893974743464
Epoch: 9,Loss : 3.889439827755739
Epoch: 9,Loss : 2.545962064641819
Epoch: 9,Loss : 3.8870964855577768
Epoch: 9,Loss : 4.15868064715584
Epoch: 10,Loss : 3.2946855293878077
Epoch: 10,Loss : 3.6161667042999
Epoch: 10,Loss : 3.7236810629190753
Epoch: 10,Loss : 3.517113460315139
Epoch: 10,Loss : 3.8858818964863366
Epoch: 10,Loss : 2.562820599769463
Epoch: 10,Loss : 3.5125877908685847
Epoch: 10,Loss : 4.2333505280889385
Epoch: 10,Loss : 4.161315585528567
Epoch: 10,Loss : 3.4668222026027156
Epoch: 10,Loss : 3.9889800888388196
Epoch: 10,Loss : 3.944003141068758
Epoch: 10,Loss : 2.599689945944293
Epoch: 10,Loss : 2.910915314044568
Epoch: 10,Loss : 4.086742174065499
Epoch: 11,Loss : 3.6172129133022617
Epoch: 11,Loss : 3.67686821411575
Epoch: 11,Loss : 3.55255692459418
Epoch: 11,Loss : 3.7075306439167957
Epoch: 11,Loss : 3.180303697372305
Epoch: 11,Loss : 3.858271963454749
Epoch: 11,Loss : 3.3812625265874017
Epoch: 11,Loss : 3.056803567797814
Epoch: 11,Loss : 3.923062021891375
Epoch: 11,Loss : 3.772645018564327
Epoch: 11,Loss : 3.981250296286997
Epoch: 11,Loss : 3.9551536245857912
Epoch: 11,Loss : 2.393436474487708
Epoch: 11,Loss : 3.043606204506201
Epoch: 11,Loss : 3.880660364472476
Epoch: 12,Loss : 3.56667863542512
Epoch: 12,Loss : 3.2986973343831743
Epoch: 12,Loss : 3.790194015929453
Epoch: 12,Loss : 3.352558324721368
Epoch: 12,Loss : 4.085419531443031
Epoch: 12,Loss : 3.0487177560348604
Epoch: 12,Loss : 2.2255130651266413
Epoch: 12,Loss : 3.1197859037923514
Epoch: 12,Loss : 4.034203052212131
Epoch: 12,Loss : 3.636666664955001
Epoch: 12,Loss : 2.791316836921289
Epoch: 12,Loss : 3.7977307831976264
Epoch: 12,Loss : 3.9489980984592146
Epoch: 12,Loss : 3.0850694157787624
Epoch: 12,Loss : 3.6164614657604397
Epoch: 13,Loss : 3.681263581884749
Epoch: 13,Loss : 3.2157130435884462
Epoch: 13,Loss : 2.8181066416789307
Epoch: 13,Loss : 3.9434384204314474
Epoch: 13,Loss : 2.939603246367088
Epoch: 13,Loss : 2.352224942948875
Epoch: 13,Loss : 3.89671886520314
Epoch: 13,Loss : 4.224104811222217
Epoch: 13,Loss : 3.898797317582873
Epoch: 13,Loss : 3.5131227973890686
Epoch: 13,Loss : 3.5751038613006783
Epoch: 13,Loss : 3.9497998315010285
Epoch: 13,Loss : 3.5079776047898226
Epoch: 13,Loss : 2.937018890090961
Epoch: 13,Loss : 1.7851463667956602
Epoch: 14,Loss : 1.7235464896410564
Epoch: 14,Loss : 3.1579243332776903
Epoch: 14,Loss : 3.731857150671221
Epoch: 14,Loss : 3.808764078655253
Epoch: 14,Loss : 3.232985852626803
Epoch: 14,Loss : 2.7268613449871824
Epoch: 14,Loss : 3.331798275536354
Epoch: 14,Loss : 4.053657332347682
Epoch: 14,Loss : 4.501559162101349
Epoch: 14,Loss : 3.2701821959252166
Epoch: 14,Loss : 3.5045817777084944
Epoch: 14,Loss : 3.2471417024497526
Epoch: 14,Loss : 4.036555558203586
Epoch: 14,Loss : 3.470107064895805
Epoch: 14,Loss : 3.1424225417394407
Epoch: 15,Loss : 3.826924467926071
Epoch: 15,Loss : 3.1812109220943094
Epoch: 15,Loss : 3.2155585094150916
Epoch: 15,Loss : 3.4490113588749582
Epoch: 15,Loss : 3.6961021667980973
Epoch: 15,Loss : 2.786374346902527
Epoch: 15,Loss : 4.11039610767636
Epoch: 15,Loss : 3.4855281792368853
Epoch: 15,Loss : 3.334046703693783
Epoch: 15,Loss : 3.2791773069630565
Epoch: 15,Loss : 3.8788168491477535
Epoch: 15,Loss : 3.4886082533674885
Epoch: 15,Loss : 2.9259115797739472
Epoch: 15,Loss : 4.043252822411924
Epoch: 15,Loss : 2.50808373450976
Epoch: 16,Loss : 3.2609472077849997
Epoch: 16,Loss : 3.1521917347234174
Epoch: 16,Loss : 3.015909235331193
Epoch: 16,Loss : 3.897874187303632
Epoch: 16,Loss : 3.975342152557987
Epoch: 16,Loss : 3.9671144820741358
Epoch: 16,Loss : 2.9459372848234926
Epoch: 16,Loss : 3.9517050219104535
Epoch: 16,Loss : 3.9129405070588787
Epoch: 16,Loss : 2.4286853709252263
Epoch: 16,Loss : 3.6266683527505332
Epoch: 16,Loss : 3.2210378782814564
Epoch: 16,Loss : 3.8010082376974403
Epoch: 16,Loss : 3.255451692515643
Epoch: 16,Loss : 2.473304105055214
Epoch: 17,Loss : 3.559679119175284
Epoch: 17,Loss : 3.5642135276720794
Epoch: 17,Loss : 4.252299093156261
Epoch: 17,Loss : 3.6364987244062688
Epoch: 17,Loss : 3.1621842079971483
Epoch: 17,Loss : 3.520990225127972
Epoch: 17,Loss : 3.1119714543982635
Epoch: 17,Loss : 3.274930461331235
Epoch: 17,Loss : 3.430715012202044
Epoch: 17,Loss : 3.094928301523849
Epoch: 17,Loss : 3.2973004997068354
Epoch: 17,Loss : 3.3308716811683143
Epoch: 17,Loss : 3.6557937791522614
Epoch: 17,Loss : 3.7888882042715277
Epoch: 17,Loss : 3.3908694830647508
Epoch: 18,Loss : 2.7968785180225644
Epoch: 18,Loss : 3.760872623338988
Epoch: 18,Loss : 3.334974711524736
Epoch: 18,Loss : 3.7910830556176323
Epoch: 18,Loss : 3.749467948381823
Epoch: 18,Loss : 3.3741499308882816
Epoch: 18,Loss : 3.387720981101161
Epoch: 18,Loss : 4.13454668090994
Epoch: 18,Loss : 3.386564479527379
Epoch: 18,Loss : 2.5859875256544975
Epoch: 18,Loss : 3.277747172148641
Epoch: 18,Loss : 3.020104828249249
Epoch: 18,Loss : 3.797157133151285
Epoch: 18,Loss : 3.5329871806635045
Epoch: 18,Loss : 3.3946849023139856
Epoch: 19,Loss : 3.7127506213228396
Epoch: 19,Loss : 3.5533603372340297
Epoch: 19,Loss : 3.4225051958572763
Epoch: 19,Loss : 2.9435673618888774
Epoch: 19,Loss : 3.4470490821970645
Epoch: 19,Loss : 3.117978216069776
Epoch: 19,Loss : 3.3232605332136367
Epoch: 19,Loss : 4.194886179689423
Epoch: 19,Loss : 3.4177610190151024
Epoch: 19,Loss : 3.841352417933272
Epoch: 19,Loss : 3.7845643093691796
Epoch: 19,Loss : 2.938822171819623
Epoch: 19,Loss : 2.991765467847873
Epoch: 19,Loss : 3.0193031398537205
Epoch: 19,Loss : 3.2640404790454656
Epoch: 20,Loss : 3.3267077854185336
Epoch: 20,Loss : 3.5827050917892302
Epoch: 20,Loss : 3.300997404101542
Epoch: 20,Loss : 2.9215012395813376
Epoch: 20,Loss : 3.127393330518275
Epoch: 20,Loss : 3.347346534380386
Epoch: 20,Loss : 2.7020122835434774
Epoch: 20,Loss : 3.1477923585093177
Epoch: 20,Loss : 3.185813990289622
Epoch: 20,Loss : 4.0859132394387565
Epoch: 20,Loss : 3.07473789057103
Epoch: 20,Loss : 3.590862845702992
Epoch: 20,Loss : 3.1912638176518997
Epoch: 20,Loss : 4.038303765653916
Epoch: 20,Loss : 4.106032751563907
Epoch: 21,Loss : 2.9362319331097178
Epoch: 21,Loss : 2.8809827943534625
Epoch: 21,Loss : 3.9094404067655124
Epoch: 21,Loss : 3.8079459576185806
Epoch: 21,Loss : 3.6556415294104783
Epoch: 21,Loss : 3.1775982651246255
Epoch: 21,Loss : 2.993893193021683
Epoch: 21,Loss : 3.206636811496967
Epoch: 21,Loss : 3.387135385965126
Epoch: 21,Loss : 3.0725050065207604
Epoch: 21,Loss : 3.45395618802733
Epoch: 21,Loss : 3.251437828947755
Epoch: 21,Loss : 3.808709669616348
Epoch: 21,Loss : 2.6010356774154744
Epoch: 21,Loss : 3.484088746891711
Epoch: 22,Loss : 3.6961843550533016
Epoch: 22,Loss : 3.693202654917659
Epoch: 22,Loss : 3.143312727001093
Epoch: 22,Loss : 3.4452395829230404
Epoch: 22,Loss : 2.8279273419715554
Epoch: 22,Loss : 3.4393472052343492
Epoch: 22,Loss : 3.2841989484583705
Epoch: 22,Loss : 3.5187211897254382
Epoch: 22,Loss : 3.4308754898517693
Epoch: 22,Loss : 3.1298547279907685
Epoch: 22,Loss : 3.5594982074110706
Epoch: 22,Loss : 2.6484329674756397
Epoch: 22,Loss : 3.2807551920530837
Epoch: 22,Loss : 3.821564236634346
Epoch: 22,Loss : 3.133204004339153
Epoch: 23,Loss : 3.2512801971407073
Epoch: 23,Loss : 3.721474502286399
Epoch: 23,Loss : 3.811253446744118
Epoch: 23,Loss : 3.7442904288680987
Epoch: 23,Loss : 2.0542384199606833
Epoch: 23,Loss : 3.3234867244028656
Epoch: 23,Loss : 2.9159732256447173
Epoch: 23,Loss : 3.0630717930407965
Epoch: 23,Loss : 3.770753648097826
Epoch: 23,Loss : 3.8912116093379305
Epoch: 23,Loss : 3.900035503316525
Epoch: 23,Loss : 2.7472089656973164
Epoch: 23,Loss : 3.5281021465130253
Epoch: 23,Loss : 2.8977218480542484
Epoch: 23,Loss : 1.8746282151392308
Epoch: 24,Loss : 3.2424919251980775
Epoch: 24,Loss : 2.7320835892421442
Epoch: 24,Loss : 4.354560056353682
Epoch: 24,Loss : 3.1742529382486016
Epoch: 24,Loss : 1.935814304983808
Epoch: 24,Loss : 2.3856377686581123
Epoch: 24,Loss : 3.65592750015719
Epoch: 24,Loss : 2.963490623918707
Epoch: 24,Loss : 3.2603146440304895
Epoch: 24,Loss : 4.024060389778286
Epoch: 24,Loss : 2.575675975055645
Epoch: 24,Loss : 3.3523383454088815
Epoch: 24,Loss : 2.895511417415956
Epoch: 24,Loss : 3.8535259411241123
Epoch: 24,Loss : 4.8813814639300706
Epoch: 25,Loss : 3.2569775004931047
Epoch: 25,Loss : 3.4103969479616456
Epoch: 25,Loss : 2.515595171482233
Epoch: 25,Loss : 2.728425179543724
Epoch: 25,Loss : 4.218740689275663
Epoch: 25,Loss : 2.6235410639244208
Epoch: 25,Loss : 3.5927844712720733
Epoch: 25,Loss : 3.583394240124476
Epoch: 25,Loss : 3.34544846470856
Epoch: 25,Loss : 1.8853978001256868
Epoch: 25,Loss : 3.7269244598341675
Epoch: 25,Loss : 3.9663330285908254
Epoch: 25,Loss : 2.442491813433865
Epoch: 25,Loss : 3.6175311480119943
Epoch: 25,Loss : 3.2681748347002966

In [32]:
print(model.weights) #better weights and bias than random given weights and bias
print(model.bias)

Parameter containing:
tensor([ 0.4863,  0.3586,  0.3526,  0.8645,  0.1874,  0.3441,  0.7801,  0.3076,
         0.5363,  0.7634,  0.2029,  0.8152,  0.2812,  0.1731,  0.0557,  0.3678,
         0.2028,  0.2191,  0.5390,  0.6420,  0.8551,  0.5737,  0.8787,  0.1567,
         0.7766,  0.5609,  0.7780, -0.0690,  0.5069,  0.3236],
       dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0006], dtype=torch.float64, requires_grad=True)

## Evaluation

In [33]:
model.eval()
accuracy_list=[]
with torch.no_grad():
    for batch_feature,batch_label in test_loader:
      #forward pass
      y_pred=model(batch_feature)
      y_pred=(y_pred>0.8).float()

      batch_accuracy=(y_pred.view(-1)==batch_label).float().mean().item()
      accuracy_list.append(batch_accuracy)

acc=sum(accuracy_list)/len(accuracy_list)
print(f"Accuracy : {acc*100}%")

Accuracy : 92.53472238779068%